name: Semgrep

on:
  push:
    branches: [ "main", "master" ]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  semgrep:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install semgrep
        run: |
          pip install semgrep

      - name: Clone semgrep community rules
        run: |
          git clone https://github.com/semgrep/semgrep-rules.git

      - name: Run Semgrep with python rules
        run: |
          semgrep scan --config semgrep-rules/python/ --error
